<?php
$activity_config=array(
	'money_type'=>array(
		0=>__('Đạo cụ'),
		1=>__('Đồng'),
		2=>__('Đồng Khóa'),
		3=>__('Nguyên Bảo'),
		4=>__('NB Khóa'),
	),
	'activity_type'=>array(
		1=>__('Hoạt động trực tuyến'),
		2=>__('Quái rơi xuống'),
		3=>__('Hoạt động thẻ'),
		5=>__('Tích lũy nạp tiền'),
		//6=>__('有福同享'),
		7=>__( 'Đổi hoạt động'),
		8=>__( 'Buff hoạt động'),
		9=>__( 'Worldcup'),
		10=>__( 'Cánh tiến hóa'),
		11=>__( 'Trang bị thần hóa'),
		12=>__( 'Bảo thạch khắc'),
		13=>__( 'Cường hóa'),
		14=>__( 'Tọa kỵ thăng giai'),
		15=>__( 'Tăng cảnh giới đồng đội'),
		16=>__( 'Điểm tiêu phí đổi'),
		17=>__( 'Hoạt động phụ bản'),
		18=>__( 'Quà Nạp'),
		19=>__( 'Đồng Đội trang bị thăng giai'),
		20=>__( 'Đồng Đội trang bị thăng cấp'),
		21=>__( 'Tọa kỵ trang bị tinh luyện'),
		22=>__( 'Võ hồn thăng cấp'),
		23=>__( 'Võ hồn tế luyện'),
		24=>__( 'Nạp vòng quay'),
	),
	'fall_type'=>array(
		1=>__('Đạo cụ đan'),
		2=>__('Tiền tài'),
		3=>__('Rơi xuống'),
	),
	'fall_model'=>array(
		0=>__('Tư hữu'),
		5=>__('Chung'),
	),
	'egg_type'=>array(
		1=>__('Trứng vàng'),
		2=>__('Trứng bạc'),
		3=>__('Trứng đồng'),
	),
	'pay_type'=>array(
		1=>__('Đạo cụ'),
		2=>__('Tiền tài'),
	),
	'pay_limit_type'=>array(
		1=>__('Tổng mua'),
		2=>__('Mỗi ngày'),
	),
	'exchange_type'=>array(
		1=>__('Đổi mục tiêu'),
		2=>__('Đổi cần'),
	),
	'occ_type'=>array(
		0=>__('Không'),
		11=>__('Phá Thiên'),
		21=>__('Vũ Nguyệt'),
		31=>__('Phi Linh'),
		41=>__('Ảo Tuyết'),
	),
	'buff_type'=>array(
		1=>__('Ôn Tuyền'),
		2=>__('EXP pb'),
		3=>__('Giết quái'),
		4=>__('Chiến trường'),
		5=>__('Cạnh kỹ trường'),
		6=>__('Vận tiêu'),
	),
	'world_reward_type'=>array(
		1=>__('Thưởng phe thắng'),
		2=>__('Bồi thường'),
	),
	'up_type_10'=>array(
		1=>__('Thăng cấp cánh'),
		2=>__('Lần tiến hóa cánh'),
	),
	'up_type_11'=>array(
		1=>__('Cấp thần hóa'),
		2=>__('Lần thần hóa'),
	),
	'up_type_12'=>array(
		1=>__('Cấp điêu khắc'),
		2=>__('Lần điêu kahwcs'),
	),
	'ride_type'=>array(
		1=>__('Lục hệ'),
	),
	'equip_fire_type'=>array(
		1=>__('Phàm hỏa'),
		2=>__('Linh hỏa'),
		3=>__('Tiên hỏa'),
		4=>__('Thần hỏa'),
		5=>__('Thánh hỏa'),
	),
	'pet_realm_type'=>array(
		1=>__('Phàm cảnh'),
		2=>__('Linh cảnh'),
		3=>__('Tiên cảnh'),
		4=>__('Thần cảnh'),
		5=>__('Thánh cảnh'),
	),
	'world_cup_item' => array(
		'Brazil',
		'Cameroon',
		'Croatia',
		'Mexico',
		'Australia',
		'Chile',
		'Hà Lan',
		'Tây Ban Nha',
		'Colombia',
		'Bờ Biển Ngà',
		'Hy Lạp',
		"Nhật Bản",
		'Costa Rica',
		'Anh',
		'Italia',
		'Uruguay',
		'Ecuador',
		'Pháp',
		'Honduras',
		'Thụy Sĩ',
		'Argentina',
		'Bosnia và Herzegovina',
		'Iran',
		'Nigeria',
		'Đức',
		'Ghana',
		'Bồ Đào Nha',
		'Hoa Kỳ',
		'Algeria',
		'Bỉ',
		'Nga',
		'Hàn Quốc'
	),
	'world_cup_win'=>array(
		0=>__('Không rõ'),
		1=>__('A thắng'),
		2=>__('B thắng'),
		3=>__('Hòa'),
	),
);
?>