<?php
//属性配置
//背包属性
$bag_attr_conf=array(
	'hp'=>__('HP'),
	'mp'=>__('MP'),
	'addhp'=>__('Tăng Sinh Mệnh'),
	'addmp'=>__('Tăng MP'),
	'vigor'=>__('Thể lực'),
	'anger'=>__('Nộ khí'),
	'attack'=>__('Công'),
	'defense'=>__('Phòng'),
	'point'=>__('Chính xác'),
	'dodge'=>__('Né'),
	'critical'=>__('Bạo'),
	'criticaldf'=>__('K.Bạo'),
	'criticaleffect'=>__('Bạo thương'),
	'criticaleffectdf'=>__('Đỡ'),
	'iceattack'=>__('Băng công'),
	'icedefense'=>__('Băng phòng'),
	'poisonattack'=>__('Độc công'),
	'poisondefense'=>__('Độc phòng'),
	'fireattack'=>__('Hỏa công'),
	'firedefense'=>__('Hỏa phòng'),
	'speed'=>__('Tốc'),
	'retreatdf'=>__('Kháng lùi'),
	'retreatdf'=>__('Kháng lùi'),
	'decspeeddf'=>__('Kháng giảm tốc'),
	'dizzydf'=>__('Kháng choáng'),
	'dizzydf'=>__('Kháng choáng'),
	'pulldf'=>__('Kháng kéo'),
	'defhpper'=>__('Ngự thương'),
	'stopdf'=>__('Kháng địng'),
	'silencedf'=>__('Kháng trầm mặc'),
);
?>